"""empty message

Revision ID: d4ed233b8429
Revises: 
Create Date: 2020-05-19 12:53:49.048917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ed233b8429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiny_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['shorturl'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiny_url', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
